export default {
  SPLASH_SCREEN: 'SPLASH_SCREEN',
  ON_BOARDING_1_SCREEN: 'ON_BOARDING_1_SCREEN',
  ON_BOARDING_2_SCREEN: 'ON_BOARDING_2_SCREEN',
  ON_BOARDING_3_SCREEN: 'ON_BOARDING_3_SCREEN',
  HOME_SCREEN: 'HOME_SCREEN',
  FAVORITE_SCREEN: 'FAVORITE_SCREEN',
  SETTINGS_SCREEN: 'SETTINGS_SCREEN',
  HOME_SCREENS_GROUP: 'HOME_SCREENS_GROUP',
};
